name: 'Terraform Destroy Core CI'

on:
  workflow_call:

jobs:
  terraform_destroy:
    name: "Terraform-destroy-core"
    if: ${{ github.event.inputs.action == 'Terraform-destroy-core' }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "./terraform/gcp-core"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      
      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VARS_FILE: terraform/terraform.tfvars